### ISSUE TITLE
fix: cascading delete fails with 409 sometimes

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/fhir-server#240] opened 2023-03-09 16:59 UTC
### 🔥 Bug Description
Deleting requests via fhir resource manager results in `409`

### 🔍 Steps to Reproduce the Bug
Following error occurs on delete requests via fhir resource manager:
```
HttpError: 409 - 

{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Requested delete operation stopped before all conflicts were handled. May need to increase the configured Maximum Delete Conflict Query Count.</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Requested delete operation stopped before all conflicts were handled. May need to increase the configured Maximum Delete Conflict Query Count."
  } ]
}
```

### 🧯 Possible Solution
increase maximum delete conflict query count
* [maybe this?](https://smilecdr.com/docs/configuration_categories/fhir_configuration.html#property-delete-child-resource-count)

**Comment by Zbozi** [comment] 2023-08-04 13:12
After trying to delete a resource that it corupted no rsources can be deleted. This is only possible after a reload.

**Comment by Zbozi** [comment] 2023-08-04 13:13
Also deletion of multiple resources leads to a 409 "... to many threads trying to delete the same resource"

**Comment by velramiir** [comment] 2023-08-24 11:35
After some research in the issues of the HAPI FHIR repository, I believe that the 409 error mentioned by @Zbozi above (409 "... too many threads trying to delete the same resource") is caused by the combination of a cascading delete and a transaction bundle.

A related issue (concurrent cascading deletes with overlapping dependencies) has already been reported https://github.com/hapifhir/hapi-fhir/issues/3889. The corresponding fix has not resolved the problem of conflicts occurring.

If a set of resources for a document (Procedure, 2 x List, 2 x QuestionnaireResponse) is grouped into a transactional delete, the operation succeeds without issues. All resources are subsequently marked as deleted on the server and requests trying to access them return 410 Gone. If a cascading delete is performed only on the Procedure, then the delete succeeds as well and is cascaded to the lists, but not the responses, as expected. The responses can then still be accessed (200), while the other 3 resources are marked as gone (410).
If, however, the transactional delete is combined with a cascading delete, the issue of concurrent deletes occurs and the result is a 409 error. In this specific case on my local machine, the result is the deletion of only the lists. My _unproven_ theory is that the server tries to roll back the failed transaction, but fails to do so correctly and thus causes an inconsistent state. Requests to the lists now return 410 Gone, but still prevent the deletion of the Procedure, as if their deletion had been rolled back correctly. Subsequent deletion attempts then cause the other version of the 409 error mentioned above by @andreakreichgauer (Requested delete operation stopped before all conflicts were handled...).

We can prevent running into this issue by using either the transactional delete or the cascading delete exclusively, depending on our use case.

**Closed by velramiir** 2023-08-24 11:35 UTC
Labels: Type: Bug

**Comment by Zbozi** [comment] 2023-09-08 13:30
Will be fixed by: https://github.com/dot-base/fhir-server/pull/246
